- name: install packages for compile protobuf
  become: true
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - make
    - gcc

- name: create tmp directory
  file: path=/tmp/ansible/protobuf state=directory

- name: download protobuf 2.5.0
  unarchive:
    src: "{{ protobuf_dist_url }}"
    dest: /tmp/ansible/protobuf
    creates: /tmp/ansible/protobuf/protobuf-2.5.0

- name: compile protobuf 2.5.0
  become: true
  shell: |
    cd /tmp/ansible/protobuf/protobuf-2.5.0 && ./configure
    cd /tmp/ansible/protobuf/protobuf-2.5.0 && make
    cd /tmp/ansible/protobuf/protobuf-2.5.0 && make check
    cd /tmp/ansible/protobuf/protobuf-2.5.0 && make install
