- name: install packages for compile protobuf
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - make
    - gcc
    - gcc-c++

- name: create protobuf directory
  file: path={{ ansible_env.HOME }}/protobuf state=directory

- name: download protobuf 2.5.0
  unarchive:
    src: "{{ protobuf_dist_url }}"
    dest: "{{ ansible_env.HOME }}/protobuf"
    remote_src: yes
    creates: "{{ ansible_env.HOME }}/protobuf/protobuf-2.5.0"

- name: compile protobuf 2.5.0
  become: yes
  shell: |
    cd {{ ansible_env.HOME }}/protobuf/protobuf-2.5.0 && ./configure
    cd {{ ansible_env.HOME }}/protobuf/protobuf-2.5.0 && make
    cd {{ ansible_env.HOME }}/protobuf/protobuf-2.5.0 && make check
    cd {{ ansible_env.HOME }}/protobuf/protobuf-2.5.0 && make install


