- name: install git and mvn
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - maven
    - git

- name: clone incubator-nemo project
  git:
    repo: "{{ nemo_git_repo_url }}"
    dest: "{{ ansible_env.HOME }}"

- name: build incubaotr-nemo project
  shell: |
    cd {{ ansible_env.HOME }}/incubator-nemo && mvn clean install -T 2C