- debug: var=is_yum_needed

- name: install apache mvn using yum
  become: yes
  yum: name=apache-maven state=present
  when: is_yum_needed

- name: install apache mvn
  become: yes
  package: name=apache-maven state=present
  when: not is_yum_needed