- name: install git and mvn
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - maven
    - git

- name: clone incubator-nemo project
  git:
    repo: "{{ nemo_git_repo_url }}"
    dest: "{{ ansible_env.HOME }}/{{ nemo_project_name }}"

- name: build incubaotr-nemo project
  command: mvn clean install -T 2C -DskipITs
  args:
    chdir: "{{ ansible_env.HOME }}/{{ nemo_project_name }}"