---
- hosts: hadoop_master
  roles:
    - { role: hadoop_common, install_mode: false, hadoop_role: master }

- hosts: hadoop_slave
  roles:
    - { role: hadoop_common, install_mode: false, hadoop_role: slave }