---
- hosts: hadoop_master
  vars:
    key_basedir: "/tmp/ansible/id_rsa_copy"
  tasks:
    - name: create .ssh
      file: path={{ ansible_env.HOME }}/.ssh state=directory

    - name: create .ssh/config
      file:
        path: "{{ ansible_env.HOME }}/.ssh/config"
        state: file
        mode: "u=rw,g=r,o=r"

    - name: create ssh key in master
      shell: ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa creates=~/.ssh/id_rsa

    - name: disable ssh host key checking
      blockinfile:
        path: "{{ ansible_env.HOME }}/.ssh/config"
        block: |
          Host *
              StrictHostKeyChecking no

    - name: create local key_basedir
      local_action:
        module: file
        path: "{{ key_basedir }}"
        state: absent
      local_action:
        module: file
        path: "{{ key_basedir }}"
        state: directory
      run_once: yes

    - fetch:
        src: "{{ ansible_env.HOME }}/.ssh/id_rsa.pub"
        dest: "{{ key_basedir }}"


- hosts: hadoop_slave
  vars:
    key_basedir: "/tmp/ansible/id_rsa_copy"
  tasks:
    - name: create .ssh on slave
      file: path={{ ansible_env.HOME }}/.ssh state=directory

    - name: create authorized_keys on slave if not exists
      file: path={{ ansible_env.HOME }}/.ssh/authorized_keys state=file

    - local_action: shell find {{ key_basedir }} -type f
      register: file_paths
      changed_when: False
      run_once: yes

    - debug: var=file_paths

    - local_action: shell cat {{ item }}
      with_items: file_paths.stdout.split()
      register: key_string
      changed_when: False
      run_once: yes

    - debug: var=key_string

    - name: add_key_string_to_authorized_keys
      lineinfile: dest={{ ansible_env.HOME }}/.ssh/authorized_keys line="{{ item.stdout }}" create=yes
      with_items: key_string.results

    - local_action:
        module: file
        path: "{{ key_basedir }}"
        mode: absent
      run_once: yes

