---
- hosts: hadoop_master
  tasks:
    - name: create .ssh
      file: path=/home/{{ ansible_user_id }}/.ssh state=directory

    - name: create .ssh/config
      file:
        path: /home/{{ ansible_user_id }}/.ssh/config
        state: file
        mode: "u=rw,g=r,o=r"

    - name: create ssh key in master
      shell: ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa creates=~/.ssh/id_rsa

    - name: disable ssh host key checking
      blockinfile:
        path: "/home/{{ ansible_user_id }}/.ssh/config"
        block: |
          Host *
              StrictHostKeyChecking no

    - shell: cat ~/.ssh/id_rsa.pub
      register: master_pub_key


- hosts: hadoop_slave
  tasks:
    - name: create .ssh on slave
      file: path=/home/{{ ansible_user_id }}/.ssh state=directory

    - name: create authorized_keys on slave if not exists
      file: path=/home/{{ ansible_user_id }}/.ssh/authorized_keys state=file

    - debug:
        var: master_pub_key

    - name: copy public key of master to authorized_keys of slaves
      lineinfile:
        line: "{{ master_pub_key.stdout }}"
        path: /home/{{ ansible_user_id }}/.ssh/id_rsa.pub

