---
- hosts: name_node
  roles:
    - hadoop_common
  tasks:
  - name: format name node
    become: yes
    become_flags: -E
    shell: $HADOOP_HOME/bin/hdfs namenode -format -force

  - name: start name node process
    become: yes
    become_flags: -E
    shell: $HADOOP_HOME/sbin/hadoop-daemon.sh --config $HADOOP_CONF_DIR --script hdfs start namenode


- hosts: data_node
  roles:
    - hadoop_common
  tasks:
  - name: start data node process
    become: yes
    become_flags: -E
    shell: $HADOOP_HOME/sbin/hadoop-daemons.sh --config $HADOOP_CONF_DIR --script hdfs start datanode
