---
- hosts: name_node
  roles:
    - hadoop_common
  tasks:
  - name: stop name node process
    become: yes
    become_flags: -E
    shell: $HADOOP_HOME/sbin/hadoop-daemon.sh --config $HADOOP_CONF_DIR --script hdfs stop namenode


- hosts: data_node
  roles:
    - hadoop_common
  tasks:
  - name: stop data node process
    become: yes
    become_flags: -E
    shell: $HADOOP_HOME/sbin/hadoop-daemons.sh --config $HADOOP_CONF_DIR --script hdfs stop datanode
