---
- name: generate slaves file to hadoop_master
  template:
    src: slaves.j2
    dest: "{{ hadoop_base_path }}/hadoop/etc/hadoop/slaves"
  when: hadoop_role | match("master")

- name: copy etc/hadoop/* from local machine
  copy:
    src: "{{ hadoop_config_files_path }}/"
    dest: "{{ hadoop_base_path }}/hadoop/etc/hadoop/"
    directory_mode: yes
    force: yes
  when: hadoop_config_files_path is defined and hadoop_config_files_path != ''

- shell: echo $JAVA_HOME
  register: java_home

- name: add java home to hadoop_env.sh
  lineinfile:
    dest: "{{ hadoop_base_path }}/hadoop/etc/hadoop/hadoop-env.sh"
    line: "export JAVA_HOME={{ java_home.stdout }}"
