---
- name: create hadoop base directory
  become: true
  file:
    state: directory
    path: "{{ hadoop_base_path }}"

- stat:
    path: "{{ hadoop_base_path }}/{{ hadoop_version }}"
  become: true
  register: hadoop_home_stats

- name: unarchive {{ hadoop_version }} file from hadoop dist url
  become: true
  unarchive:
    src: "{{ hadoop_dist_url }}"
    dest: "{{ hadoop_base_path }}"
  when: not hadoop_home_stats.stat.exists

- name: make a symbolic link from {{ hadoop_version }} to {{ hadoop_base_path }}/hadoop
  become: true
  file:
    src: "{{ hadoop_base_path }}/{{ hadoop_version }}"
    dest: "{{ hadoop_base_path }}/hadoop"
    state: link

- name: setup hadoop environment variables
  become: true
  template:
    src: hadoop_env.sh.j2
    dest: /etc/profile.d/