---
- name: install java
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ java_version }}"
    - "{{ java_version }}-devel"

- name: setup java environment variables
  become: yes
  template:
    src: java_env.sh
    dest: /etc/profile.d/java_env.sh